### ISSUE TITLE
Documentation bugs?

### ISSUE THREAD

**Issue by jbclements** [massung/tabular-asa#4]
* It appears that table-map returns a sequence, not a table.
* The textual description of table-map did not make sense to me. I would instead write:
"Call proc with every row in the table represented as a list. Return the result as a sequence. A list of columns may be provided, which is equivalent to (table-map (table-cut t cols) proc)" ... unless of course I'm mistaken? 

Are there other functions that return sequences that are documented as returning tables?

**Comment by jbclements** [comment]
I also did not understand the `table-apply` docs at all, I would instead write something like this:
"Like table-map, but rather than calling the procedure with a single argument (a list of values), calls the procedure with `n` arguments, where `n` is the number of columns in the given table. In other words, (table-apply t proc cols) is equivalent to (table-apply t (lambda (row) (apply proc row)) cols)"

**Comment by jbclements** [comment]
Also, a simple typo in pretty-print-rows:

"Controls the nmaximum umber of rows output by [write-table]" Should instead start "Controls the maximum number of rows..."

**Comment by jbclements** [comment]
Let me know if you accept pull requests?

**Comment by jbclements** [comment]
It looks like `build-column` isn't `provide`d ?

**Comment by massung** [comment]
@jbclements - Been a while since I looked at the repo and code. Let me read through and catch up a bit. But thank you so much for the issues (if nothing else, I love seeing my code being used by others!). 

I absolutely accept pull requests as long as there's an attempt to stay consistent with the coding style. So if you have suggestions, please feel free.

For `build-column` not provided, I'll have to try and remember if that was intentional or not (and "why" if not, otherwise just provide it).

Your documentation suggestions are definitely better.

**Comment by massung** [comment]
Looking through, the documentation for `table-map` and `table-apply` is wrong (they should return `sequence?`). The reason for this is that I didn't want to try and create a table automatically and pick column names. It's trivial enough to just wrap them in a call to `table-read/sequence` and create a new table from those results.

I like your documentation suggestions for them. Let me know if you plan on making a PR or not. If not, I'll update the docs. If you plan to, can you also update the return type?

**Comment by massung** [comment]
Fixed docs via 349fdb7. Please feel free to open a PR with better docs and I'm happy to look at them!

Exposed `build-column` and `empty-column` (which was also documented, but not exposed) in ce819c1. Thanks for finding that!
